-- Maintenant ajouter les données de test

-- 1. Insérer des données de test pour PROJECTS avec images
INSERT INTO projects (title, description, content, technologies, github_url, demo_url, is_active, featured, image_url) VALUES
('Système de Sécurité Cyber', 'Solution complète de cybersécurité pour entreprises', '# Système de Sécurité Cyber\n\nUne solution complète de cybersécurité développée pour protéger les infrastructures critiques des entreprises.\n\n## Fonctionnalités\n- Détection d''intrusions en temps réel\n- Analyse comportementale avancée\n- Dashboard de monitoring\n- Alertes automatisées\n\n## Technologies utilisées\n- Python pour l''analyse\n- React pour l''interface\n- Machine Learning pour la détection', ARRAY['Python', 'React', 'Machine Learning', 'PostgreSQL'], 'https://github.com/admin/cyber-security', 'https://demo-cyber.example.com', true, true, 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=600&fit=crop'),

('Plateforme E-commerce Sécurisée', 'Plateforme de vente en ligne avec sécurité renforcée', '# Plateforme E-commerce Sécurisée\n\nUne plateforme de commerce électronique développée avec les plus hauts standards de sécurité.\n\n## Sécurité\n- Chiffrement end-to-end\n- Authentification multi-facteurs\n- Prévention des attaques XSS/CSRF\n- Audit de sécurité automatisé\n\n## Performance\n- Architecture microservices\n- Cache Redis\n- CDN global\n- Optimisations SQL avancées', ARRAY['Node.js', 'Vue.js', 'Redis', 'Docker'], 'https://github.com/admin/secure-ecommerce', 'https://demo-shop.example.com', true, true, 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop'),

('Application Mobile de Monitoring', 'App mobile pour surveiller les systèmes à distance', '# Application Mobile de Monitoring\n\nApplication mobile native permettant de surveiller les systèmes informatiques à distance.\n\n## Fonctionnalités\n- Monitoring en temps réel\n- Notifications push\n- Graphiques interactifs\n- Mode hors ligne\n\n## Compatibilité\n- iOS et Android\n- Synchronisation cloud\n- Interface adaptative\n- Support multi-langues', ARRAY['React Native', 'Firebase', 'GraphQL', 'TypeScript'], 'https://github.com/admin/monitoring-app', 'https://apps.apple.com/monitoring', true, false, 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop'),

('Outil d''Analyse de Vulnérabilités', 'Scanner automatisé de vulnérabilités web', '# Outil d''Analyse de Vulnérabilités\n\nScanner automatisé capable de détecter les vulnérabilités dans les applications web.\n\n## Capacités\n- Scan OWASP Top 10\n- Détection SQL Injection\n- Analyse XSS\n- Audit de configuration\n\n## Rapports\n- PDF détaillés\n- Dashboard interactif\n- Suggestions de correction\n- Tracking des corrections', ARRAY['Python', 'Django', 'Celery', 'PostgreSQL'], 'https://github.com/admin/vulnerability-scanner', 'https://scanner.example.com', true, false, 'https://images.unsplash.com/photo-1563206767-5b18f218e8de?w=800&h=600&fit=crop');

-- 2. Insérer des données de test pour BLOGS avec images
INSERT INTO blogs (title, content, excerpt, published, featured, tags, slug, image_url) VALUES
('Les Nouvelles Menaces Cyber en 2024', '# Les Nouvelles Menaces Cyber en 2024\n\nLe paysage de la cybersécurité évolue constamment. En 2024, nous observons l''émergence de nouvelles menaces sophistiquées.\n\n## Principales tendances\n\n### 1. Attaques basées sur l''IA\nLes cybercriminels utilisent désormais l''intelligence artificielle pour :\n- Créer des deepfakes convaincants\n- Automatiser les attaques de phishing\n- Générer des malwares polymorphes\n\n### 2. Ransomware-as-a-Service\nLe modèle RaaS continue de se développer :\n- Barrière d''entrée réduite\n- Spécialisation des rôles\n- Professionnalisation du crime\n\n### 3. Attaques sur les infrastructures cloud\n- Misconfiguration des services\n- Élévation de privilèges\n- Latéral movement\n\n## Recommandations\n- Mise à jour continue des systèmes\n- Formation du personnel\n- Implémentation de l''authentification multi-facteurs\n- Surveillance proactive des réseaux', 'Découvrez les nouvelles menaces cybersécurité qui émergent en 2024 et comment s''en protéger efficacement.', true, true, ARRAY['cybersécurité', 'menaces', '2024', 'IA'], 'nouvelles-menaces-cyber-2024', 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&h=600&fit=crop'),

('Mise en Place d''une Architecture Zero Trust', '# Architecture Zero Trust : Guide Complet\n\nL''architecture Zero Trust révolutionne l''approche traditionnelle de la sécurité réseau.\n\n## Qu''est-ce que Zero Trust ?\n\nLe principe "Never Trust, Always Verify" remplace le modèle de sécurité périmétrique traditionnel.\n\n### Piliers fondamentaux\n1. **Vérification explicite** : Authentifier et autoriser basé sur tous les points de données\n2. **Accès de moindre privilège** : Limiter l''accès avec Just-In-Time et Just-Enough-Access\n3. **Assumer la compromission** : Minimiser le rayon d''impact et segmenter l''accès\n\n## Implémentation pratique\n\n### Phase 1 : Cartographie\n- Inventaire des actifs\n- Flux de données\n- Identification des utilisateurs\n\n### Phase 2 : Micro-segmentation\n- Segmentation réseau\n- Politiques granulaires\n- Monitoring continu\n\n### Phase 3 : Automatisation\n- Orchestration de sécurité\n- Réponse automatisée\n- Analytics comportementaux\n\n## Bénéfices mesurés\n- Réduction de 75% des incidents de sécurité\n- Amélioration de 40% de la posture de sécurité\n- ROI positif en 18 mois', 'Guide complet pour implémenter une architecture Zero Trust dans votre organisation.', true, true, ARRAY['zero-trust', 'architecture', 'sécurité-réseau'], 'architecture-zero-trust-guide', 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=600&fit=crop'),

('DevSecOps : Intégrer la Sécurité dans le CI/CD', '# DevSecOps : Sécurité Native dans le Pipeline\n\nL''intégration de la sécurité dans les pipelines DevOps n''est plus optionnelle.\n\n## Qu''est-ce que DevSecOps ?\n\nDevSecOps intègre les pratiques de sécurité dès le début du cycle de développement.\n\n### Shift Left Security\n- Tests de sécurité précoces\n- Scan de vulnérabilités automatisé\n- Revue de code sécurisée\n\n## Pipeline sécurisé\n\n### Phase de développement\n```bash\n# Exemple de pipeline sécurisé\nstages:\n  - lint\n  - security-scan\n  - test\n  - build\n  - deploy\n```\n\n### Outils essentiels\n1. **SAST** : Analyse statique du code\n2. **DAST** : Tests dynamiques\n3. **IAST** : Analyse interactive\n4. **SCA** : Analyse des composants\n\n### Métriques clés\n- Time to detection\n- Time to resolution\n- Vulnérabilités par release\n- Couverture des tests de sécurité\n\n## Automatisation\n- Gates de sécurité automatiques\n- Remédiation assistée\n- Reporting continu\n\n## Culture DevSecOps\n- Formation des équipes\n- Responsabilité partagée\n- Amélioration continue', 'Apprenez à intégrer efficacement la sécurité dans vos pipelines DevOps avec DevSecOps.', true, false, ARRAY['devsecops', 'ci-cd', 'automatisation'], 'devsecops-integration-securite', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=600&fit=crop'),

('Gestion des Incidents de Sécurité : Playbook 2024', '# Playbook de Gestion d''Incidents de Sécurité\n\nUn guide pratique pour une réponse efficace aux incidents cybersécurité.\n\n## Phases de réponse\n\n### 1. Préparation\n- Constitution de l''équipe CSIRT\n- Développement des procédures\n- Formation régulière\n- Tests de simulation\n\n### 2. Détection et Analyse\n- Monitoring 24/7\n- Corrélation d''événements\n- Classification des incidents\n- Escalade appropriée\n\n### 3. Containment\n- Isolation immédiate\n- Préservation des preuves\n- Communication interne\n- Mesures temporaires\n\n### 4. Éradication\n- Identification de la cause racine\n- Suppression des traces\n- Patch des vulnérabilités\n- Renforcement des défenses\n\n### 5. Récupération\n- Restauration des services\n- Monitoring renforcé\n- Tests de validation\n- Retour à la normale\n\n### 6. Leçons apprises\n- Analyse post-incident\n- Documentation des améliorations\n- Mise à jour des procédures\n- Formation adaptée\n\n## Outils recommandés\n- SOAR platforms\n- Threat intelligence\n- Forensic tools\n- Communication sécurisée\n\n## Métriques d''efficacité\n- MTTD (Mean Time To Detect)\n- MTTR (Mean Time To Respond)\n- Coût par incident\n- Taux de récurrence', 'Playbook complet pour gérer efficacement les incidents de cybersécurité dans votre organisation.', true, false, ARRAY['incident-response', 'csirt', 'playbook'], 'gestion-incidents-securite-playbook', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=600&fit=crop');