-- Simplification de toutes les descriptions de projets pour retirer les informations confidentielles

-- 1. PFE Santé-App
UPDATE projects 
SET content = E'## 📋 Contexte du projet\n\nProjet de fin d\'études visant à créer un écosystème complet de e-santé permettant le suivi médical des patients et la gestion des consultations par les professionnels de santé.\n\n## 🎯 Objectifs\n\n- Créer une plateforme web responsive pour le suivi médical\n- Développer une API REST sécurisée\n- Concevoir une application mobile pour les patients\n- Garantir la sécurité et la confidentialité des données médicales\n\n## 🔧 Technologies utilisées\n\n**Frontend Web** : React, Chart.js, Tailwind CSS\n**Backend** : Laravel avec authentification JWT\n**Mobile** : React Native avec notifications push\n\n## 💡 Compétences développées\n\n- Architecture full-stack complète\n- Sécurisation des données sensibles (chiffrement, HTTPS)\n- Développement mobile multiplateforme\n- Gestion de projet et méthodologie Agile\n- Conformité RGPD pour les données médicales\n\n## 📊 Résultats\n\n✅ Plateforme multi-plateforme fonctionnelle\n✅ Authentification sécurisée\n✅ Interface utilisateur intuitive\n✅ Documentation technique complète'
WHERE title = 'PFE – Santé-App (React / Laravel / React-Native)';

-- 2. CyberDéfense & Sécurité Web
UPDATE projects 
SET content = E'## 📋 Contexte du projet\n\nMise en place d\'un laboratoire de sécurité applicative pour comprendre et corriger les vulnérabilités web les plus critiques.\n\n## 🎯 Objectifs\n\n- Créer un environnement d\'apprentissage sécurisé\n- Identifier et exploiter les failles OWASP Top 10\n- Implémenter les correctifs de sécurité\n- Documenter les bonnes pratiques\n\n## 🔧 Technologies et outils\n\nDocker, DVWA, WebGoat, Burp Suite, Kali Linux\n\n## 💡 Vulnérabilités étudiées\n\n### Injection SQL (SQLi)\nÉtude des techniques d\'exploitation et mise en place de requêtes préparées pour la protection.\n\n### Cross-Site Scripting (XSS)\nAnalyse des différents types (Reflected, Stored, DOM-based) et implémentation de Content Security Policy.\n\n### Cross-Site Request Forgery (CSRF)\nÉtude des attaques et mise en place de tokens de protection.\n\n### Autres vulnérabilités\nAuthentification cassée, exposition de données sensibles, contrôle d\'accès défaillant.\n\n## 🎓 Compétences développées\n\nPentest web, sécurité applicative, OWASP Top 10, remédiation de vulnérabilités, audit de code'
WHERE title = 'CyberDéfense & Sécurité Web';

-- 3. Automatisation Inventaire
UPDATE projects 
SET content = E'## 📋 Contexte du projet\n\nDéveloppement d\'un script Python pour automatiser l\'inventaire des équipements réseau et leur intégration dans le système de gestion d\'actifs.\n\n## 🎯 Objectifs\n\n- Automatiser la collecte d\'informations sur les équipements réseau\n- Intégrer automatiquement les données dans le système de gestion\n- Réduire le temps d\'inventaire\n- Éliminer les erreurs de saisie manuelle\n\n## 🔧 Stack technique\n\nPython, Paramiko (SSH), API REST, parsing de données\n\n## 💡 Fonctionnalités développées\n\n- Connexion SSH automatisée aux équipements\n- Collecte d\'informations matérielles et logicielles\n- Parsing intelligent des données\n- Intégration via API REST\n- Gestion des erreurs et logs détaillés\n\n## 📊 Résultats\n\n✅ Réduction de 95% du temps d\'inventaire\n✅ Élimination des erreurs humaines\n✅ Données toujours à jour\n\n## 🎓 Compétences développées\n\nAutomatisation Python, API REST, SSH, parsing de données, gestion d\'erreurs'
WHERE title = 'Automatisation Inventaire GLPI – LNE';

-- 4. Migration Exchange
UPDATE projects 
SET content = E'## 📋 Contexte du projet\n\nMigration de dossiers publics Exchange vers des boîtes aux lettres partagées modernes pour améliorer les performances et la compatibilité.\n\n## 🎯 Objectifs\n\n- Migrer les dossiers publics vers des boîtes partagées\n- Préserver l\'intégralité des données\n- Maintenir les droits d\'accès\n- Zéro interruption de service\n\n## 🔧 Technologies utilisées\n\nExchange Server, Active Directory, PowerShell\n\n## 💡 Processus de migration\n\n### Analyse et planification\nInventaire complet, cartographie des droits, mesure des volumes de données.\n\n### Migration des données\nExport et import des données avec vérification d\'intégrité.\n\n### Migration des permissions\nTranscription des droits d\'accès vers le nouveau système.\n\n## 📊 Résultats\n\n✅ Migration complète sans perte de données\n✅ Permissions correctement transcrites\n✅ Performance améliorée significativement\n✅ Infrastructure modernisée\n\n## 🎓 Compétences développées\n\nAdministration Exchange, PowerShell, gestion de permissions, migration de données'
WHERE title = 'Migration Dossiers Publics Exchange – LNE';

-- 5. Optimisation PDQ
UPDATE projects 
SET content = E'## 📋 Contexte du projet\n\nRésolution de problèmes de déploiement logiciel et d\'inventaire automatisé causés par des configurations réseau.\n\n## 🎯 Objectifs\n\n- Rétablir le fonctionnement du système de déploiement\n- Résoudre les problèmes de connectivité\n- Automatiser la configuration\n- Documenter la solution\n\n## 🔧 Technologies utilisées\n\nPDQ Deploy/Inventory, PowerShell, Configuration réseau\n\n## 💡 Diagnostic et résolution\n\nAnalyse des logs, identification du problème de configuration réseau, mise en place de la solution et automatisation du processus.\n\n## 📊 Résultats\n\n✅ Déploiements automatiques rétablis\n✅ Inventaire temps réel opérationnel\n✅ Gain de temps de 95%\n✅ Documentation complète créée\n\n## 🎓 Compétences développées\n\nDépannage système, configuration réseau, PowerShell, automatisation'
WHERE title = 'Optimisation PDQ Deploy / Inventory – LNE';

-- 6. Sécurisation GPO
UPDATE projects 
SET content = E'## 📋 Contexte du projet\n\nRenforcement de la sécurité réseau via stratégies de groupe Active Directory pour limiter les accès et sécuriser les postes de travail.\n\n## 🎯 Objectifs\n\n- Bloquer l\'accès Internet sur postes sensibles\n- Masquer les paramètres réseau aux utilisateurs\n- Maintenir la flexibilité pour les administrateurs\n- Assurer la traçabilité\n\n## 🔧 Technologies utilisées\n\nActive Directory, Group Policy, Windows Server, PowerShell, Windows Firewall\n\n## 💡 Stratégies implémentées\n\n- Règles de pare-feu pour isolation réseau\n- Désactivation de la configuration automatique\n- Masquage des paramètres réseau\n- Durcissement de la sécurité générale\n\n## 📊 Résultats\n\n✅ Sécurité renforcée significativement\n✅ Déploiement centralisé\n✅ Conformité aux standards de sécurité\n✅ Documentation technique complète\n\n## 🎓 Compétences développées\n\nStratégies de groupe Active Directory, sécurité Windows, gestion des permissions'
WHERE title = 'Sécurisation Réseau via GPO – LNE';